import type { Activity } from './types'

// Real La Union activities — verified locations, March 2026
// [AC-ACTIVITIES-F1]
export const ACTIVITIES: Activity[] = [
  // ── MORNING ───────────────────────────────────────────────────────────────
  {
    id: 'surf-01',
    name: 'Surfing Lesson at Urbiztondo',
    category: 'morning',
    vibe: ['beach', 'adventure'],
    address: 'Urbiztondo Beach, San Juan, La Union',
    lat: 16.6590,
    lng: 120.3218,
    hours: '6:00 AM – 10:00 AM',
    description: 'Beginner-friendly surf lessons with certified local instructors. Best waves hit in the early morning.',
  },
  {
    id: 'yoga-01',
    name: 'Sunrise Beach Yoga',
    category: 'morning',
    vibe: ['beach', 'leisure'],
    address: 'Urbiztondo Beachfront, San Juan, La Union',
    lat: 16.6595,
    lng: 120.3222,
    hours: '6:00 AM – 8:00 AM',
    description: 'Guided yoga session on the sand at sunrise. Perfect way to start the day before the beach gets crowded.',
  },
  {
    id: 'hike-01',
    name: 'Tangadan Falls Hike',
    category: 'morning',
    vibe: ['adventure', 'nature'],
    address: 'San Gabriel, La Union',
    lat: 16.6234,
    lng: 120.4012,
    hours: '6:00 AM – 12:00 PM',
    description: 'Trek through lush mountains to reach the stunning Tangadan Falls. Moderate difficulty, about 2-3 hours round trip.',
  },
  {
    id: 'bike-01',
    name: 'Bike Ride along MacArthur Highway',
    category: 'morning',
    vibe: ['adventure', 'sightseeing'],
    address: 'MacArthur Highway, San Juan, La Union',
    lat: 16.6620,
    lng: 120.3240,
    hours: '6:00 AM – 9:00 AM',
    description: 'Rent bikes and cruise along the scenic La Union coastline. Easy ride, great ocean views.',
  },

  // ── AFTERNOON ─────────────────────────────────────────────────────────────
  {
    id: 'beach-01',
    name: 'Pebble Beach & Tarec Beach Hopping',
    category: 'afternoon',
    vibe: ['beach', 'leisure', 'sightseeing'],
    address: 'Pebble Beach, Bacnotan, La Union',
    lat: 16.7012,
    lng: 120.3340,
    hours: '10:00 AM – 5:00 PM',
    description: 'Visit the famous pebble beach and nearby Tarec Beach. Perfect for photos, swimming, and chilling.',
  },
  {
    id: 'kayak-01',
    name: 'Kayaking at the Bay',
    category: 'afternoon',
    vibe: ['beach', 'adventure'],
    address: 'Urbiztondo Bay, San Juan, La Union',
    lat: 16.6605,
    lng: 120.3215,
    hours: '9:00 AM – 4:00 PM',
    description: 'Rent kayaks and paddle around the calm bay. Stunning views of the coast from the water.',
  },
  {
    id: 'spa-01',
    name: 'Massage & Spa at Elyu Strip',
    category: 'afternoon',
    vibe: ['leisure'],
    address: 'Urbiztondo Strip, San Juan, La Union',
    lat: 16.6600,
    lng: 120.3220,
    hours: '10:00 AM – 6:00 PM',
    description: 'Full body massage at one of the many affordable spa centers along the strip. Very relaxing.',
  },
  {
    id: 'shop-01',
    name: 'Souvenir Shopping at San Fernando',
    category: 'afternoon',
    vibe: ['sightseeing', 'leisure'],
    address: 'San Fernando Public Market, La Union',
    lat: 16.6155,
    lng: 120.3183,
    hours: '8:00 AM – 5:00 PM',
    description: 'Pick up pasalubong and local crafts at San Fernando market. Also famous for ukay-ukay finds.',
  },
  {
    id: 'temple-01',
    name: 'Ma-Cho Temple Visit',
    category: 'afternoon',
    vibe: ['sightseeing', 'nature'],
    address: 'Ma-Cho Temple, San Fernando, La Union',
    lat: 16.6150,
    lng: 120.3175,
    hours: '9:00 AM – 5:00 PM',
    description: 'Visit the iconic Chinese hilltop temple with panoramic views of the Lingayen Gulf. Stairs are a workout!',
  },
  {
    id: 'snorkel-01',
    name: 'Snorkeling at Aringay',
    category: 'afternoon',
    vibe: ['beach', 'adventure', 'nature'],
    address: 'Aringay, La Union',
    lat: 16.5974,
    lng: 120.3225,
    hours: '9:00 AM – 4:00 PM',
    description: 'Crystal-clear waters for snorkeling with colorful reef fish. Rent gear on site.',
  },

  // ── EVENING ───────────────────────────────────────────────────────────────
  {
    id: 'sunset-01',
    name: 'Sunset Watching at Urbiztondo',
    category: 'evening',
    vibe: ['beach', 'leisure', 'sightseeing'],
    address: 'Urbiztondo Beachfront, San Juan, La Union',
    lat: 16.6620,
    lng: 120.3240,
    hours: '5:00 PM – 7:00 PM',
    description: 'The iconic La Union sunset. The most beautiful time to be on the beach — bring drinks.',
  },
  {
    id: 'bonfire-01',
    name: 'Beach Bonfire & Drinks',
    category: 'evening',
    vibe: ['beach', 'nightlife', 'leisure'],
    address: 'Urbiztondo Beach, San Juan, La Union',
    lat: 16.6590,
    lng: 120.3218,
    hours: '6:00 PM – 10:00 PM',
    description: 'Arrange a group bonfire on the beach with cold drinks and good vibes. Some hostels offer this service.',
  },
  {
    id: 'bar-01',
    name: 'Flotsam & Jetsam Beach Party',
    category: 'evening',
    vibe: ['nightlife', 'beach', 'adventure'],
    address: 'Flotsam & Jetsam, Urbiztondo Beach, San Juan',
    lat: 16.6616,
    lng: 120.3245,
    hours: '8:00 PM – 3:00 AM',
    description: 'The most famous party venue in Elyu. Live music, fire shows, dancing until dawn.',
  },
  {
    id: 'karaoke-01',
    name: 'Karaoke Night',
    category: 'evening',
    vibe: ['nightlife', 'leisure'],
    address: 'San Juan, La Union',
    lat: 16.6580,
    lng: 120.3210,
    hours: '7:00 PM – 12:00 AM',
    description: 'A classic Filipino night out — belt your heart out at a local KTV. Always a good time.',
  },
  {
    id: 'strip-01',
    name: 'Night Walk along the Strip',
    category: 'evening',
    vibe: ['sightseeing', 'nightlife', 'leisure'],
    address: 'Urbiztondo Strip, San Juan, La Union',
    lat: 16.6610,
    lng: 120.3230,
    hours: '7:00 PM – 11:00 PM',
    description: 'Stroll the buzzing Urbiztondo strip at night — street food, live music, and good vibes all around.',
  },
]

export const ACTIVITY_MAP: Record<string, Activity> = Object.fromEntries(
  ACTIVITIES.map((a) => [a.id, a])
)
