import type { Venue } from './types'

// Real La Union venues — verified coordinates, March 2026
// Urbiztondo / San Juan area

export const RESTAURANTS: Venue[] = [
  // ── BREAKFAST / MORNING CAFÉS (7–10 AM) ────────────────────────────────────
  {
    id: 'b-01',
    name: 'El Union Coffee',
    category: 'breakfast',
    vibe: ['café'],
    address: 'MacArthur Highway, Urbiztondo, San Juan, La Union',
    lat: 16.6596395,
    lng: 120.3223696,
    hours: '7:00 AM – 10:00 PM',
    description: 'One of the most famous cafés in La Union — viral horchata, grilled cheese, surfer vibe, and very Instagrammable. Usually crowded.',
  },
  {
    id: 'b-02',
    name: 'Clean Beach Coffee',
    category: 'breakfast',
    vibe: ['café', 'casual dining'],
    address: 'Urbiztondo Beachfront, San Juan, La Union',
    lat: 16.6621100,
    lng: 120.3238470,
    hours: '7:00 AM – 9:00 PM',
    description: 'Beachfront café with great ocean views. Known for smoothie bowls and coffee.',
  },
  {
    id: 'b-03',
    name: 'The Coffee Library San Juan',
    category: 'breakfast',
    vibe: ['café'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6563141,
    lng: 120.3211403,
    hours: '7:00 AM – 9:00 PM',
    description: 'Travel-themed café famous for Vietnamese coffee and pho. Good brunch location.',
  },
  {
    id: 'b-04',
    name: 'Masa Bakehouse La Union',
    category: 'breakfast',
    vibe: ['café'],
    address: 'San Juan, La Union',
    lat: 16.6715329,
    lng: 120.3429384,
    hours: '7:00 AM – 5:00 PM',
    description: 'One of the best pastry spots in Elyu — famous for croissants, sourdough, and brunch plates.',
  },
  {
    id: 'b-05',
    name: 'Curo La Union',
    category: 'breakfast',
    vibe: ['casual dining'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6589199,
    lng: 120.3306647,
    hours: '7:00 AM – 10:00 PM',
    description: 'Popular all-day breakfast and brunch restaurant. Good for sit-down breakfast.',
  },

  // ── LUNCH (12–2 PM) ────────────────────────────────────────────────────────
  {
    id: 'l-01',
    name: 'Tagpuan Sa San Juan',
    category: 'lunch',
    vibe: ['casual dining'],
    address: 'San Juan, La Union',
    lat: 16.658650,
    lng: 120.321850,
    hours: '10:00 AM – 10:00 PM',
    description: 'Famous for Ilocano dishes — bagnet, sinanglaw. One of the most recommended local food spots.',
  },
  {
    id: 'l-02',
    name: 'Seabuds',
    category: 'lunch',
    vibe: ['café', 'casual dining'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6570618,
    lng: 120.3201926,
    hours: '8:00 AM – 8:00 PM',
    description: 'Vegan café with tropical ambiance. Good healthy bowls and smoothies.',
  },
  {
    id: 'l-03',
    name: 'Little Canggu',
    category: 'lunch',
    vibe: ['café', 'casual dining'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6620702,
    lng: 120.3241228,
    hours: '8:00 AM – 9:00 PM',
    description: 'Bali-style café. Good lunch: rice bowls, smoothie bowls.',
  },
  {
    id: 'l-04',
    name: 'Surf Shack',
    category: 'lunch',
    vibe: ['casual dining', 'bar'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.659000,
    lng: 120.321700,
    hours: '10:00 AM – 10:00 PM',
    description: 'Casual surfer restaurant with pizza and seafood meals.',
  },

  // ── SUNSET / DINNER ────────────────────────────────────────────────────────
  {
    id: 'd-01',
    name: 'Kabsat La Union',
    category: 'dinner',
    vibe: ['casual dining', 'party'],
    address: 'San Juan, La Union',
    lat: 16.665520,
    lng: 120.315700,
    hours: '11:00 AM – 11:00 PM',
    description: 'Famous sunset dining restaurant with large beach-view seating.',
  },
  {
    id: 'd-02',
    name: 'Olas Banditos',
    category: 'dinner',
    vibe: ['casual dining', 'bar'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.658330,
    lng: 120.322230,
    hours: '11:00 AM – 11:00 PM',
    description: 'Very popular Mexican restaurant — tacos and burritos.',
  },
  {
    id: 'd-03',
    name: 'La Kantina by Kermit',
    category: 'dinner',
    vibe: ['casual dining', 'bar'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.660000,
    lng: 120.322900,
    hours: '5:00 PM – 12:00 AM',
    description: 'Italian food and cocktails. Good dinner vibe.',
  },

  // ── NIGHTLIFE / BARS (After Dinner) ────────────────────────────────────────
  {
    id: 'd-04',
    name: 'Flotsam and Jetsam',
    category: 'dinner',
    vibe: ['bar', 'party'],
    address: 'Urbiztondo Beach, San Juan, La Union',
    lat: 16.661620,
    lng: 120.324500,
    hours: 'Open 24 hours',
    description: 'One of the most famous party hostels and bars in Elyu.',
  },
  {
    id: 'd-05',
    name: 'Tavern By The Sea',
    category: 'dinner',
    vibe: ['bar', 'party'],
    address: 'Urbiztondo Beach, San Juan, La Union',
    lat: 16.659900,
    lng: 120.322400,
    hours: '6:00 PM – 2:00 AM',
    description: 'Beachfront bar with DJs.',
  },
  {
    id: 'd-06',
    name: 'Ugly Bar',
    category: 'dinner',
    vibe: ['bar', 'party'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.661200,
    lng: 120.324200,
    hours: '8:00 PM – 3:00 AM',
    description: 'Popular night bar for music and drinks.',
  },
]

export const VENUE_MAP: Record<string, Venue> = Object.fromEntries(
  RESTAURANTS.map((v) => [v.id, v])
)
