import type { Venue } from './types'

// La Union, Philippines coordinates center: 16.6197° N, 120.3199° E
// Seed data: replace with real venues before launch
// All lat/lng are approximate coords for La Union surf and dining area (San Juan / San Fernando)

export const RESTAURANTS: Venue[] = [
  // ── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    id: 'b-01',
    name: 'Elyu Café',
    category: 'breakfast',
    vibe: ['café', 'casual dining'],
    address: 'National Highway, San Juan, La Union',
    lat: 16.6728,
    lng: 120.3236,
    description: 'Chill beachside café serving specialty coffee and all-day breakfast bowls.',
  },
  {
    id: 'b-02',
    name: 'Morning Waves Diner',
    category: 'breakfast',
    vibe: ['casual dining', 'street food'],
    address: 'Urbiztondo Beach, San Juan, La Union',
    lat: 16.6710,
    lng: 120.3221,
    description: 'Local diner famous for tapsilog and fresh fruit shakes by the beach.',
  },
  {
    id: 'b-03',
    name: 'Bask Café & Grill',
    category: 'breakfast',
    vibe: ['café', 'casual dining'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6715,
    lng: 120.3228,
    description: 'Instagrammable spot with acai bowls, toasts, and single-origin coffee.',
  },
  {
    id: 'b-04',
    name: 'Silog Street',
    category: 'breakfast',
    vibe: ['street food'],
    address: 'Macalva Norte, San Fernando, La Union',
    lat: 16.6195,
    lng: 120.3197,
    description: 'Beloved street-side spot for danggut, longganisa, and other La Union classics.',
  },
  {
    id: 'b-05',
    name: 'El Union Coffee',
    category: 'breakfast',
    vibe: ['café'],
    address: 'Urbiztondo Beach Road, San Juan, La Union',
    lat: 16.6720,
    lng: 120.3230,
    description: 'OG La Union café, world-famous cold brew and surfer-friendly vibes.',
  },

  // ── LUNCH ──────────────────────────────────────────────────────────────────
  {
    id: 'l-01',
    name: 'Flotsam & Jetsam',
    category: 'lunch',
    vibe: ['casual dining', 'bar'],
    address: 'Urbiztondo Beach, San Juan, La Union',
    lat: 16.6705,
    lng: 120.3218,
    description: 'Bohemian beach hostel & bar with killer seafood tacos and fresh buko drinks.',
  },
  {
    id: 'l-02',
    name: 'Halo-Halo de Iloko',
    category: 'lunch',
    vibe: ['street food', 'casual dining'],
    address: 'Quezon Ave, San Fernando, La Union',
    lat: 16.6180,
    lng: 120.3185,
    description: 'Iconic La Union dessert stop — also serves steaming bowls of pinakbet and bagnet.',
  },
  {
    id: 'l-03',
    name: 'Bananas & Boards',
    category: 'lunch',
    vibe: ['casual dining', 'bar'],
    address: 'Surf Road, San Juan, La Union',
    lat: 16.6725,
    lng: 120.3240,
    description: 'Surf camp kitchen with fresh grilled fish, veggie bowls, and cold beer on the deck.',
  },
  {
    id: 'l-04',
    name: 'La Union Esplanade Food Park',
    category: 'lunch',
    vibe: ['street food', 'party'],
    address: 'Poro Point, San Fernando, La Union',
    lat: 16.6335,
    lng: 120.3105,
    description: 'Open-air food park with 20+ stalls covering isaw to sushi bake.',
  },
  {
    id: 'l-05',
    name: 'Tagpuan sa La Union',
    category: 'lunch',
    vibe: ['buffet', 'casual dining'],
    address: 'National Highway, San Fernando, La Union',
    lat: 16.6210,
    lng: 120.3190,
    description: 'Buffet-style lunch spot serving Ilocano specialties — pinakbet, dinengdeng, bagnet.',
  },
  {
    id: 'l-06',
    name: 'Surf City Grill',
    category: 'lunch',
    vibe: ['casual dining', 'bar'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6718,
    lng: 120.3233,
    description: 'Wood-fired grills, cold San Mig, and the best view of the surf break.',
  },

  // ── DINNER ─────────────────────────────────────────────────────────────────
  {
    id: 'd-01',
    name: 'Kahuna Beach Resort Bar & Grill',
    category: 'dinner',
    vibe: ['party', 'bar'],
    address: 'Urbiztondo Beach, San Juan, La Union',
    lat: 16.6700,
    lng: 120.3215,
    description: 'Legendary beachfront party spot — live music, fire shows, and bucket drinks.',
  },
  {
    id: 'd-02',
    name: 'Circle Hostel Rooftop Bar',
    category: 'dinner',
    vibe: ['bar', 'party', 'casual dining'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6722,
    lng: 120.3238,
    description: 'Rooftop bar with sunset views, craft cocktails, and live acoustic sets.',
  },
  {
    id: 'd-03',
    name: 'Fat Lips Surf Shop & Bar',
    category: 'dinner',
    vibe: ['bar', 'casual dining'],
    address: 'Urbiztondo Beach Road, San Juan, La Union',
    lat: 16.6712,
    lng: 120.3225,
    description: 'Surf culture bar serving loaded burgers, wings, and the best mojitos in LU.',
  },
  {
    id: 'd-04',
    name: 'Ilocano Feast — Bagnet House',
    category: 'dinner',
    vibe: ['casual dining', 'buffet'],
    address: 'San Fernando City, La Union',
    lat: 16.6190,
    lng: 120.3195,
    description: 'Authentic Ilocano dinner — crispy bagnet, empanada, and pinakbet for groups.',
  },
  {
    id: 'd-05',
    name: 'Jungle Boogie',
    category: 'dinner',
    vibe: ['party', 'bar'],
    address: 'Urbiztondo, San Juan, La Union',
    lat: 16.6708,
    lng: 120.3220,
    description: 'After-dinner party spot — DJs, bucket cocktails, and a dance floor by the beach.',
  },
  {
    id: 'd-06',
    name: 'Sebang Ilocano Cuisine',
    category: 'dinner',
    vibe: ['casual dining'],
    address: 'Carlatan, San Fernando, La Union',
    lat: 16.6155,
    lng: 120.3172,
    description: 'Family-style Ilocano dinner with authentic dinakdakan, igado, and bagnet.',
  },
]

export const VENUE_MAP: Record<string, Venue> = Object.fromEntries(
  RESTAURANTS.map((v) => [v.id, v])
)
