'use client'
// [AC-AITINPDF-F3, F5, F6]
// Dynamically imported via useItineraryDownload — never statically imported in server components
// @react-pdf/renderer uses browser canvas APIs; must be loaded client-side only
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import type { GeneratedItinerary, TripConfig, ItineraryMeal } from '@/app/lib/types'

interface Props {
  itinerary: GeneratedItinerary
  tripConfig: TripConfig
}

// [SOLID:SRP] — styles separated from rendering logic
const s = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header: { marginBottom: 24 },
  tripName: { fontSize: 22, fontWeight: 'bold', color: '#1a3c5e', marginBottom: 6 },
  subtitle: { fontSize: 11, color: '#6b7280', marginBottom: 2 },
  dayCard: { marginBottom: 20, padding: 16, backgroundColor: '#f0f9ff', borderRadius: 8 },
  dayTitle: { fontSize: 14, fontWeight: 'bold', color: '#0369a1', marginBottom: 10 },
  mealRow: { marginBottom: 10, paddingLeft: 8 },
  mealLabel: { fontSize: 9, fontWeight: 'bold', textTransform: 'uppercase', color: '#9ca3af', marginBottom: 2 },
  venueName: { fontSize: 12, fontWeight: 'bold', color: '#111827', marginBottom: 2 },
  venueNoVote: { fontSize: 12, color: '#9ca3af', fontStyle: 'italic', marginBottom: 2 },
  venueAddress: { fontSize: 9, color: '#6b7280', marginBottom: 2 },
  mealMeta: { fontSize: 9, color: '#374151' },
  travelNote: { fontSize: 9, color: '#6b7280', fontStyle: 'italic', marginTop: 2 },
  divider: { borderBottomColor: '#e5e7eb', borderBottomWidth: 1, marginVertical: 6 },
  footer: { position: 'absolute', bottom: 20, left: 40, right: 40 },
  footerText: { fontSize: 8, color: '#d1d5db', textAlign: 'center' },
})

function formatDate(iso: string): string {
  const d = new Date(iso + 'T00:00:00')
  return d.toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
}

function MealEntry({ meal }: { meal: ItineraryMeal }) {
  const hasVote = meal.venue !== 'No votes yet'
  return (
    <View style={s.mealRow}>
      <Text style={s.mealLabel}>{meal.meal}</Text>
      <Text style={hasVote ? s.venueName : s.venueNoVote}>{meal.venue}</Text>
      {hasVote && meal.address ? (
        <Text style={s.venueAddress}>{meal.address}</Text>
      ) : null}
      {hasVote && meal.suggestedTime !== '—' ? (
        <Text style={s.mealMeta}>
          {meal.suggestedTime} · {meal.duration}
        </Text>
      ) : null}
      {hasVote && meal.travelNote && meal.travelNote !== '—' ? (
        <Text style={s.travelNote}>💡 {meal.travelNote}</Text>
      ) : null}
    </View>
  )
}

export default function ItineraryPDF({ itinerary, tripConfig }: Props) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        {/* [AC-AITINPDF-F6] Header */}
        <View style={s.header}>
          <Text style={s.tripName}>{tripConfig.trip_name}</Text>
          <Text style={s.subtitle}>
            {formatDate(tripConfig.start_date)} – {formatDate(tripConfig.end_date)}
          </Text>
          <Text style={s.subtitle}>Stay: {tripConfig.stay_name}</Text>
        </View>

        {/* [AC-AITINPDF-F3, F5] Days */}
        {itinerary.days.map((day) => (
          <View key={day.day} style={s.dayCard}>
            <Text style={s.dayTitle}>
              Day {day.day} — {formatDate(day.date)}
            </Text>
            {day.meals.map((meal, i) => (
              <View key={meal.meal}>
                <MealEntry meal={meal} />
                {i < day.meals.length - 1 ? <View style={s.divider} /> : null}
              </View>
            ))}
          </View>
        ))}

        {/* Footer */}
        <View style={s.footer} fixed>
          <Text style={s.footerText}>
            Generated by La Union Outing Planner · {new Date().toLocaleDateString('en-PH')}
          </Text>
        </View>
      </Page>
    </Document>
  )
}
